name: ğŸš€ Build for Production ğŸ› ï¸

on:
  workflow_dispatch:

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: ğŸ“¥ Checkout
      - uses: pnpm/action-setup@v4
        name: ğŸ“¦ Setup pnpm
        with:
          version: latest
      - uses: actions/setup-node@v4
        name: ğŸš€ Setup Node.js environment
        with:
          node-version: 19.9.0
          cache: pnpm
      - name: ğŸ“¥ Install dependencies
        run: pnpm install
      - name: ğŸ—ï¸ Build
        run: pnpm build
      - uses: planetoftheweb/copy-to-branches@v1.3
        name: ğŸ“„ Copy files to production branch
        env:
          key: production
          files: |
            ./dist/**/*
            package.json
